wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1659763751
    t:
      1:
      - 1
      - 53
      - 55
      3:
      - 16
      4: 3.8.13
      5: 0.12.19
      8:
      - 5
batch_size:
  desc: null
  value: 2
epochs:
  desc: null
  value: 5000
learning_rate:
  desc: null
  value: 1.0e-09
optimizer:
  desc: null
  value: adam
